on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Build Docker image
      #   run: docker build -t my-python-app .

      # - name: Run Docker container
      #   run: docker run my-python-app

      - name: "login to docker hub"
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "docker image"
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python_script .

      - name: "push to dockerhub"
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python_script
